// DO NOT EDIT, THIS FILE IS GENERATED FROM api.json
package godot

import kotlin.Int

open class HTTPClient internal constructor() : Reference() {
  companion object {
    val METHOD_CONNECT: Int = 7

    val METHOD_DELETE: Int = 4

    val METHOD_GET: Int = 0

    val METHOD_HEAD: Int = 1

    val METHOD_MAX: Int = 9

    val METHOD_OPTIONS: Int = 5

    val METHOD_PATCH: Int = 8

    val METHOD_POST: Int = 2

    val METHOD_PUT: Int = 3

    val METHOD_TRACE: Int = 6

    val RESPONSE_ACCEPTED: Int = 202

    val RESPONSE_ALREADY_REPORTED: Int = 208

    val RESPONSE_BAD_GATEWAY: Int = 502

    val RESPONSE_BAD_REQUEST: Int = 400

    val RESPONSE_CONFLICT: Int = 409

    val RESPONSE_CONTINUE: Int = 100

    val RESPONSE_CREATED: Int = 201

    val RESPONSE_EXPECTATION_FAILED: Int = 417

    val RESPONSE_FAILED_DEPENDENCY: Int = 424

    val RESPONSE_FORBIDDEN: Int = 403

    val RESPONSE_FOUND: Int = 302

    val RESPONSE_GATEWAY_TIMEOUT: Int = 504

    val RESPONSE_GONE: Int = 410

    val RESPONSE_HTTP_VERSION_NOT_SUPPORTED: Int = 505

    val RESPONSE_IM_A_TEAPOT: Int = 418

    val RESPONSE_IM_USED: Int = 226

    val RESPONSE_INSUFFICIENT_STORAGE: Int = 507

    val RESPONSE_INTERNAL_SERVER_ERROR: Int = 500

    val RESPONSE_LENGTH_REQUIRED: Int = 411

    val RESPONSE_LOCKED: Int = 423

    val RESPONSE_LOOP_DETECTED: Int = 508

    val RESPONSE_METHOD_NOT_ALLOWED: Int = 405

    val RESPONSE_MISDIRECTED_REQUEST: Int = 421

    val RESPONSE_MOVED_PERMANENTLY: Int = 301

    val RESPONSE_MULTIPLE_CHOICES: Int = 300

    val RESPONSE_MULTI_STATUS: Int = 207

    val RESPONSE_NETWORK_AUTH_REQUIRED: Int = 511

    val RESPONSE_NON_AUTHORITATIVE_INFORMATION: Int = 203

    val RESPONSE_NOT_ACCEPTABLE: Int = 406

    val RESPONSE_NOT_EXTENDED: Int = 510

    val RESPONSE_NOT_FOUND: Int = 404

    val RESPONSE_NOT_IMPLEMENTED: Int = 501

    val RESPONSE_NOT_MODIFIED: Int = 304

    val RESPONSE_NO_CONTENT: Int = 204

    val RESPONSE_OK: Int = 200

    val RESPONSE_PARTIAL_CONTENT: Int = 206

    val RESPONSE_PAYMENT_REQUIRED: Int = 402

    val RESPONSE_PERMANENT_REDIRECT: Int = 308

    val RESPONSE_PRECONDITION_FAILED: Int = 412

    val RESPONSE_PRECONDITION_REQUIRED: Int = 428

    val RESPONSE_PROCESSING: Int = 102

    val RESPONSE_PROXY_AUTHENTICATION_REQUIRED: Int = 407

    val RESPONSE_REQUESTED_RANGE_NOT_SATISFIABLE: Int = 416

    val RESPONSE_REQUEST_ENTITY_TOO_LARGE: Int = 413

    val RESPONSE_REQUEST_HEADER_FIELDS_TOO_LARGE: Int = 431

    val RESPONSE_REQUEST_TIMEOUT: Int = 408

    val RESPONSE_REQUEST_URI_TOO_LONG: Int = 414

    val RESPONSE_RESET_CONTENT: Int = 205

    val RESPONSE_SEE_OTHER: Int = 303

    val RESPONSE_SERVICE_UNAVAILABLE: Int = 503

    val RESPONSE_SWITCHING_PROTOCOLS: Int = 101

    val RESPONSE_SWITCH_PROXY: Int = 306

    val RESPONSE_TEMPORARY_REDIRECT: Int = 307

    val RESPONSE_TOO_MANY_REQUESTS: Int = 429

    val RESPONSE_UNAUTHORIZED: Int = 401

    val RESPONSE_UNAVAILABLE_FOR_LEGAL_REASONS: Int = 451

    val RESPONSE_UNPROCESSABLE_ENTITY: Int = 422

    val RESPONSE_UNSUPPORTED_MEDIA_TYPE: Int = 415

    val RESPONSE_UPGRADE_REQUIRED: Int = 426

    val RESPONSE_USE_PROXY: Int = 305

    val RESPONSE_VARIANT_ALSO_NEGOTIATES: Int = 506

    val STATUS_BODY: Int = 7

    val STATUS_CANT_CONNECT: Int = 4

    val STATUS_CANT_RESOLVE: Int = 2

    val STATUS_CONNECTED: Int = 5

    val STATUS_CONNECTING: Int = 3

    val STATUS_CONNECTION_ERROR: Int = 8

    val STATUS_DISCONNECTED: Int = 0

    val STATUS_REQUESTING: Int = 6

    val STATUS_RESOLVING: Int = 1

    val STATUS_SSL_HANDSHAKE_ERROR: Int = 9

    fun new(): HTTPClient {
      TODO()
    }
  }
}
