// DO NOT EDIT, THIS FILE IS GENERATED FROM api.json
package godot

import kotlin.Int

open class PhysicsServer internal constructor() : Object() {
  companion object {
    val AREA_BODY_ADDED: Int = 0

    val AREA_BODY_REMOVED: Int = 1

    val AREA_PARAM_ANGULAR_DAMP: Int = 6

    val AREA_PARAM_GRAVITY: Int = 0

    val AREA_PARAM_GRAVITY_DISTANCE_SCALE: Int = 3

    val AREA_PARAM_GRAVITY_IS_POINT: Int = 2

    val AREA_PARAM_GRAVITY_POINT_ATTENUATION: Int = 4

    val AREA_PARAM_GRAVITY_VECTOR: Int = 1

    val AREA_PARAM_LINEAR_DAMP: Int = 5

    val AREA_PARAM_PRIORITY: Int = 7

    val AREA_SPACE_OVERRIDE_COMBINE: Int = 1

    val AREA_SPACE_OVERRIDE_COMBINE_REPLACE: Int = 2

    val AREA_SPACE_OVERRIDE_DISABLED: Int = 0

    val AREA_SPACE_OVERRIDE_REPLACE: Int = 3

    val AREA_SPACE_OVERRIDE_REPLACE_COMBINE: Int = 4

    val BODY_AXIS_ANGULAR_X: Int = 8

    val BODY_AXIS_ANGULAR_Y: Int = 16

    val BODY_AXIS_ANGULAR_Z: Int = 32

    val BODY_AXIS_LINEAR_X: Int = 1

    val BODY_AXIS_LINEAR_Y: Int = 2

    val BODY_AXIS_LINEAR_Z: Int = 4

    val BODY_MODE_CHARACTER: Int = 3

    val BODY_MODE_KINEMATIC: Int = 1

    val BODY_MODE_RIGID: Int = 2

    val BODY_MODE_STATIC: Int = 0

    val BODY_PARAM_ANGULAR_DAMP: Int = 5

    val BODY_PARAM_BOUNCE: Int = 0

    val BODY_PARAM_FRICTION: Int = 1

    val BODY_PARAM_GRAVITY_SCALE: Int = 3

    val BODY_PARAM_LINEAR_DAMP: Int = 4

    val BODY_PARAM_MASS: Int = 2

    val BODY_PARAM_MAX: Int = 6

    val BODY_STATE_ANGULAR_VELOCITY: Int = 2

    val BODY_STATE_CAN_SLEEP: Int = 4

    val BODY_STATE_LINEAR_VELOCITY: Int = 1

    val BODY_STATE_SLEEPING: Int = 3

    val BODY_STATE_TRANSFORM: Int = 0

    val CONE_TWIST_JOINT_BIAS: Int = 2

    val CONE_TWIST_JOINT_RELAXATION: Int = 4

    val CONE_TWIST_JOINT_SOFTNESS: Int = 3

    val CONE_TWIST_JOINT_SWING_SPAN: Int = 0

    val CONE_TWIST_JOINT_TWIST_SPAN: Int = 1

    val G6DOF_JOINT_ANGULAR_DAMPING: Int = 13

    val G6DOF_JOINT_ANGULAR_ERP: Int = 16

    val G6DOF_JOINT_ANGULAR_FORCE_LIMIT: Int = 15

    val G6DOF_JOINT_ANGULAR_LIMIT_SOFTNESS: Int = 12

    val G6DOF_JOINT_ANGULAR_LOWER_LIMIT: Int = 10

    val G6DOF_JOINT_ANGULAR_MOTOR_FORCE_LIMIT: Int = 18

    val G6DOF_JOINT_ANGULAR_MOTOR_TARGET_VELOCITY: Int = 17

    val G6DOF_JOINT_ANGULAR_RESTITUTION: Int = 14

    val G6DOF_JOINT_ANGULAR_UPPER_LIMIT: Int = 11

    val G6DOF_JOINT_FLAG_ENABLE_ANGULAR_LIMIT: Int = 1

    val G6DOF_JOINT_FLAG_ENABLE_LINEAR_LIMIT: Int = 0

    val G6DOF_JOINT_FLAG_ENABLE_LINEAR_MOTOR: Int = 5

    val G6DOF_JOINT_FLAG_ENABLE_MOTOR: Int = 4

    val G6DOF_JOINT_LINEAR_DAMPING: Int = 4

    val G6DOF_JOINT_LINEAR_LIMIT_SOFTNESS: Int = 2

    val G6DOF_JOINT_LINEAR_LOWER_LIMIT: Int = 0

    val G6DOF_JOINT_LINEAR_MOTOR_FORCE_LIMIT: Int = 6

    val G6DOF_JOINT_LINEAR_MOTOR_TARGET_VELOCITY: Int = 5

    val G6DOF_JOINT_LINEAR_RESTITUTION: Int = 3

    val G6DOF_JOINT_LINEAR_UPPER_LIMIT: Int = 1

    val HINGE_JOINT_BIAS: Int = 0

    val HINGE_JOINT_FLAG_ENABLE_MOTOR: Int = 1

    val HINGE_JOINT_FLAG_USE_LIMIT: Int = 0

    val HINGE_JOINT_LIMIT_BIAS: Int = 3

    val HINGE_JOINT_LIMIT_LOWER: Int = 2

    val HINGE_JOINT_LIMIT_RELAXATION: Int = 5

    val HINGE_JOINT_LIMIT_SOFTNESS: Int = 4

    val HINGE_JOINT_LIMIT_UPPER: Int = 1

    val HINGE_JOINT_MOTOR_MAX_IMPULSE: Int = 7

    val HINGE_JOINT_MOTOR_TARGET_VELOCITY: Int = 6

    val INFO_ACTIVE_OBJECTS: Int = 0

    val INFO_COLLISION_PAIRS: Int = 1

    val INFO_ISLAND_COUNT: Int = 2

    val JOINT_6DOF: Int = 4

    val JOINT_CONE_TWIST: Int = 3

    val JOINT_HINGE: Int = 1

    val JOINT_PIN: Int = 0

    val JOINT_SLIDER: Int = 2

    val PIN_JOINT_BIAS: Int = 0

    val PIN_JOINT_DAMPING: Int = 1

    val PIN_JOINT_IMPULSE_CLAMP: Int = 2

    val SHAPE_BOX: Int = 3

    val SHAPE_CAPSULE: Int = 4

    val SHAPE_CONCAVE_POLYGON: Int = 7

    val SHAPE_CONVEX_POLYGON: Int = 6

    val SHAPE_CUSTOM: Int = 9

    val SHAPE_CYLINDER: Int = 5

    val SHAPE_HEIGHTMAP: Int = 8

    val SHAPE_PLANE: Int = 0

    val SHAPE_RAY: Int = 1

    val SHAPE_SPHERE: Int = 2

    val SLIDER_JOINT_ANGULAR_LIMIT_DAMPING: Int = 15

    val SLIDER_JOINT_ANGULAR_LIMIT_LOWER: Int = 12

    val SLIDER_JOINT_ANGULAR_LIMIT_RESTITUTION: Int = 14

    val SLIDER_JOINT_ANGULAR_LIMIT_SOFTNESS: Int = 13

    val SLIDER_JOINT_ANGULAR_LIMIT_UPPER: Int = 11

    val SLIDER_JOINT_ANGULAR_MOTION_DAMPING: Int = 18

    val SLIDER_JOINT_ANGULAR_MOTION_RESTITUTION: Int = 17

    val SLIDER_JOINT_ANGULAR_MOTION_SOFTNESS: Int = 16

    val SLIDER_JOINT_ANGULAR_ORTHOGONAL_DAMPING: Int = 21

    val SLIDER_JOINT_ANGULAR_ORTHOGONAL_RESTITUTION: Int = 20

    val SLIDER_JOINT_ANGULAR_ORTHOGONAL_SOFTNESS: Int = 19

    val SLIDER_JOINT_LINEAR_LIMIT_DAMPING: Int = 4

    val SLIDER_JOINT_LINEAR_LIMIT_LOWER: Int = 1

    val SLIDER_JOINT_LINEAR_LIMIT_RESTITUTION: Int = 3

    val SLIDER_JOINT_LINEAR_LIMIT_SOFTNESS: Int = 2

    val SLIDER_JOINT_LINEAR_LIMIT_UPPER: Int = 0

    val SLIDER_JOINT_LINEAR_MOTION_DAMPING: Int = 7

    val SLIDER_JOINT_LINEAR_MOTION_RESTITUTION: Int = 6

    val SLIDER_JOINT_LINEAR_MOTION_SOFTNESS: Int = 5

    val SLIDER_JOINT_LINEAR_ORTHOGONAL_DAMPING: Int = 10

    val SLIDER_JOINT_LINEAR_ORTHOGONAL_RESTITUTION: Int = 9

    val SLIDER_JOINT_LINEAR_ORTHOGONAL_SOFTNESS: Int = 8

    val SLIDER_JOINT_MAX: Int = 22

    val SPACE_PARAM_BODY_ANGULAR_VELOCITY_DAMP_RATIO: Int = 6

    val SPACE_PARAM_BODY_ANGULAR_VELOCITY_SLEEP_THRESHOLD: Int = 4

    val SPACE_PARAM_BODY_LINEAR_VELOCITY_SLEEP_THRESHOLD: Int = 3

    val SPACE_PARAM_BODY_MAX_ALLOWED_PENETRATION: Int = 2

    val SPACE_PARAM_BODY_TIME_TO_SLEEP: Int = 5

    val SPACE_PARAM_CONSTRAINT_DEFAULT_BIAS: Int = 7

    val SPACE_PARAM_CONTACT_MAX_SEPARATION: Int = 1

    val SPACE_PARAM_CONTACT_RECYCLE_RADIUS: Int = 0

    val SPACE_PARAM_TEST_MOTION_MIN_CONTACT_DEPTH: Int = 8
  }
}
